<?php
include 'connect.php';

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSV export</title>
    <!-- yeh aik library ha jis se csv mein data export krskte -->
    <script src="csvtable/table-to-csv.min.js"></script>
</head>
<body>


<?php include 'header.php' ?>

  <a href="#" class="btn btn-success" id="btnDownload" >Download Report</a>

  <table class="table" id="mytable" >
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Salary</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Aqib</td>
            <td>$4985</td>
            <td><a href="">Edit</a></td>
        </tr>
         <tr>
            <td>2</td>
            <td>Owais</td>
            <td>$383</td>
             <td><a href="">Edit</a></td>
        </tr>
    </tbody>
  </table>


  <script>
    //yeh autogenerated code ha us library ka hamain sirf table id, filename, ignore column aur btn download ki id ko change krna hota ha
    function main() {
        const tableToCSV = new TableToCSV("#mytable", {
            filename: "demoreport.csv",
            delimiter: ",", //delimiter (optional) default value ","
            ignoreColumns: [3], //column index (optional)
        });
        //download button > dynamic js > non blocking async await
  document.querySelector("#btnDownload").addEventListener("click", (e) => {
    tableToCSV.download();
  });
}
main();
  </script>
</body>
</html>